apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: backend
type: Opaque
data:
  DB_HOST: bGFiLWJkLmNkZGprejhxcXk4cC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  DB_NAME: aW5mcmFlc3RydWN0dXJhX2Ri
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: ZWxtYW11dHF1ZXJpYXZvbGFyMTIzNA==
