version: "3.9"

services:
  backend:
    image: 445642902280.dkr.ecr.us-east-1.amazonaws.com/users-api:latest
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db

  notification:
    image: 445642902280.dkr.ecr.us-east-1.amazonaws.com/notification-service:latest
    container_name: notification
    ports:
      - "5000:5000"
    depends_on:
      - backend

  frontend:
    image: 445642902280.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
      - notification

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: infraestructura_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2705
    ports:
      - "5432:5432"
